trigger:
  branches:
    include:
    - '*' 

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  displayName: 'Switch to triggered branch'
  inputs:
    script: |
      set -ex
      git checkout "$BUILD_SOURCEBRANCHNAME"
    workingDirectory: '$(Build.SourcesDirectory)'
- task: CmdLine@2
  displayName: 'Push updates to Github'
  inputs:
    script: |
      set -ex
      git remote add mirror https://$(GITHUB_ACCESS_TOKEN)@github.com/$(GITHUB_REPO).git
      git push mirror --force
    workingDirectory: '$(Build.SourcesDirectory)'
